name: alerta_com
description: "Aplicación de alerta comunitaria."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core y servicios
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.1

  # Imagen y edición
  image_picker: ^1.1.2
  flutter_quill: ^11.4.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
